LPS-134711 portal-search-web: remove unused dependencies
partial backport of LPS-129930 Removed unused dependencies for unit tests 208d0f396bbab0cdd01f9d210fc4021d6dacd47b
partial backport of LPS-129997 LPS-129997 portal-search-web: FIX: java.lang.NoClassDefFoundError 784fe3871e1e43a2316aa37f3b8ef856b5133cba

https://issues.liferay.com/browse/LPS-134711